#!/bin/bash
boot2docker init
boot2docker start
$(boot2docker shellinit)
echo " "
echo "================================================"
echo 'Your Docker host IP is:'
boot2docker ip
echo "================================================"
echo " "
docker run -e NODE_ENV=development -t -it --entrypoint="/nodejs/bin/npm" -i -v `pwd` --publish 80:80 my/project run dev


# Kill the docker container on exit, rather than leaving it running.
# This mimics the expected behavior of running a process locally.
function cleanup {
  myvar=`docker ps -q`
  docker kill "$myvar"
}
trap cleanup EXIT
